Update test-runner.yml

diff --git a/.github/workflows/test-runner.yml b/.github/workflows/test-runner.yml
--- a/.github/workflows/test-runner.yml
+++ b/.github/workflows/test-runner.yml
@@ -28,7 +28,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: vault • read jfrog creds
+      - name: vault • read jfrog creds (oidc)
         id: vault
         uses: hashicorp/vault-action@v3
         with:
@@ -41,6 +41,10 @@ jobs:
             ci/data/artifactory repo_docker  | ART_DOCKER_REPO;
             ci/data/artifactory username     | ART_USER;
             ci/data/artifactory password     | ART_PASS;
+
+      - name: debug • inspect OIDC token
+        run: |
+          echo "${ACTIONS_ID_TOKEN}" | cut -d '.' -f2 | base64 -d | jq || echo "OIDC token inspection failed"
 
       - name: docker • login jfrog
         run: echo "$ART_PASS" | docker login "$ART_URL" -u "$ART_USER" --password-stdin
@@ -82,7 +86,7 @@ jobs:
     runs-on: [self-hosted, Linux, X64]
     needs: ci
     steps:
-      - name: vault • read jfrog creds
+      - name: vault • read jfrog creds (oidc)
         id: vault
         uses: hashicorp/vault-action@v3
         with:
